### ISSUE TITLE
Lifetime Setting not Passed from Kodi to TVServer

### ISSUE THREAD

**Issue by boyelectron** [margro/TVServerXBMC#13]
Using Kodi 16.0, TVServerKodi v1.12.0.131, and MP2 TVServer v1.12.0 the recording lifetime setting is not passed to MP2 TVServer.  All scheduled recordings are listed in TVServer configuration / Schedules as "Keep all" regardless of the the lifetime setting in Kodi.  For example, with a lifetime of 1 week the recordings remain unto the HDD becomes full (over one month).

Is this a plugin issue, and Kodi issue, or a TVServer issue?

**Comment by popy2k14** [comment]
Its a plugin issue of the kodi addon.
I have diffed into the code and "Keep all" (calue 3) ist set hardcoded in the addon.
For v17.3 i have made a patch that it sets it to "until full".
Here is the link: https://github.com/kodi-pvr/pvr.mediaportal.tvserver/issues/70

Sadly, margo dont want to change the default value from "Keep all" to "until full" because maybe someone do not want that the old recordings gets deleted.

An option is the only solution, but i am not so deep in addon programming to change this in the addon.
Have just hot fixed the setting to my needs and compiled the addon.

Maybe when ill find time i will try to implement the wanted option/solution.
Please also write the request into the kodi thread (linked in first post of the above link).
Maybe margo, and others, will see your post and try to implement it too :-)

pOpY

**Comment by margro** [comment]
@popy2k14: This is a different issue.
I just tested this with Kodi 16.1, MediaPortal TVServer 1.17.0 and plugin 1.15.0.137 and I see the following when adding a timer in Kodi with a lifetime of 3 weeks (from today), I see that this is correctly added to the database with the keepDate set to 2017-09-30. However, the TVServer Schedules view indeed shows "Keep all". If I check the settings in MediaPortal itself, it is also showing 2017-09-30 as keep until date. So, the database contents seem to be correct, but the TV Server Schedules view does not show the keep until setting. Need to dive into this further to check whether I have to fix something.
This potential bug is for sure not in the Kodi plugin. It is either the TVServerKodi plugin or a display issue in the TVServer itself.

**Comment by margro** [comment]
When I add a similar schedule in MediaPortal itself with a Keep Until date set, the database entries are similar (with keepDate set to the correct date) and the TVServer Schedules view show also "Keep all", so I think the issue of @boyelectron is just a display bug of the TVServer itself.

**Comment by popy2k14** [comment]
thx, margo for clearing things up in this issue.
OT: Is it possible for you to add a option that users can select a default for recordings (in my case MPTV_KEEP_UNTIL_SPACE_NEEDED). My kodi plugin skills aren't so good.

thx

**Comment by margro** [comment]
Closing this old issue. Feel free to reopen if it is still relevant
