### ISSUE TITLE
Option hide or move "all channels" TV group

### ISSUE THREAD

**Issue by jojo141185** [margro/TVServerXBMC#8]
In Mediaportal TV-Server Backend I created several groups with my favorite Tv channels (Favorites, Sports, Music, ...). All these groups with the channels and epg data are flawlesly imported into the pvr Database of XBMC. Additional the group "all channels" including all tv channels of all groups is created and shows up on top priority when I start liveTV section in XBMC.
Is it possible to add an Option that hides the "all channels" group in XBMC? Another solution could be simply moving the "all channels" group to the end of the list. But in XBMC TV setting I found no options to change the order of the TV groups.

**Comment by margro** [comment]
The addon itself is already skipping the "All channels" group since XBMC/Kodi has its own "All channels" group, therefore closing this issue.
See: https://github.com/margro/xbmc-pvr-addons/blob/Gotham/addons/pvr.mediaportal.tvserver/src/pvrclient-mediaportal.cpp#L799

For hiding the XBMC/Kodi internal 'All Channels', do a feature request in the PVR Development section of the Kodi.tv forum.
